spring:
  datasource:
    url: jdbc:mysql://localhost:3310/xdml
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true